export { cadastroCommand } from './cadastro';
export { criarCommand } from './criar';
export { helpCommand } from './help';
export { voltarCommand } from './voltar';
export { tarefasCommand } from './tarefas';
export { editarCommand } from './editar';
export { sairCommand } from './sair';
export { infoCommand } from './info';
export { feitoCommand } from './feito';
